Update README.md
y0bibyte/playframework pull request #1
Opened 2021-03-31 11:57 UTC by r0gergunn

# Pull Request Checklist

* [ ] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [ ] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [ ] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ ] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [ ] Have you added copyright headers to new files?
* [ ] Have you checked that both Scala and Java APIs are updated?
* [ ] Have you updated the documentation for both Scala and Java sections?
* [ ] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #xxxx

## Purpose

What does this PR do?

## Background Context

Why did you take this approach?

## References

Are there any relevant issues / PRs / mailing lists discussions?

2021-03-31 12:23 UTC, yorlov commented
Regular comment

2021-03-31 14:20 UTC, r0gergunn commented
Comment

2021-03-31 14:23 UTC, yorlov commented
Comment

2021-03-31 16:06 UTC, yorlov commented
Comment 3

2021-03-31 17:01 UTC, yorlov commented
Comment 4

2021-04-01 09:58 UTC, yorlov requested changes
Yo

2021-04-01 09:58 UTC, yorlov commented on README.md
> -[![Gitter](https://img.shields.io/gitter/room/gitterHQ/gitter.svg)](https://gitter.im/playframework/playframework?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) [<img src=
Hm

2021-04-01 09:58 UTC, yorlov commented on README.md
>  ## Learn More
Oops

2021-04-01 12:14 UTC, yorlov commented on README.md
>  ## Learn More
reply

2021-04-01 12:14 UTC, yorlov approved these changes
Ik

2021-04-01 14:23 UTC, yorlov commented on README.md
> -[![Gitter](https://img.shields.io/gitter/room/gitterHQ/gitter.svg)](https://gitter.im/playframework/playframework?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) [<img src=
asdasd

2021-04-01 14:30 UTC, yorlov commented
Regular

2021-04-01 14:30 UTC, yorlov commented
Re 2

2021-04-01 14:31 UTC, yorlov reviewed
fd

2021-04-06 05:21 UTC, yorlov commented
Comment

2021-04-06 05:57 UTC, yorlov commented
Hi

2021-04-06 08:13 UTC, yorlov commented on README.md
> -[![Gitter](https://img.shields.io/gitter/room/gitterHQ/gitter.svg)](https://gitter.im/playframework/playframework?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) [<img src=
Hm

2021-04-06 08:17 UTC, r0gergunn commented on README.md
> -[![Gitter](https://img.shields.io/gitter/room/gitterHQ/gitter.svg)](https://gitter.im/playframework/playframework?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) [<img src=
Reply

2021-04-06 08:19 UTC, yorlov commented on README.md
> -[![Gitter](https://img.shields.io/gitter/room/gitterHQ/gitter.svg)](https://gitter.im/playframework/playframework?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) [<img src=
No

2021-04-06 10:06 UTC, r0gergunn commented on README.md
> -[![Gitter](https://img.shields.io/gitter/room/gitterHQ/gitter.svg)](https://gitter.im/playframework/playframework?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) [<img src=
ye?

2021-04-06 10:06 UTC, yorlov commented on README.md
> -[![Gitter](https://img.shields.io/gitter/room/gitterHQ/gitter.svg)](https://gitter.im/playframework/playframework?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) [<img src=
ok

2021-04-06 10:34 UTC, yorlov requested changes

2021-04-06 10:34 UTC, yorlov commented on README.md
>  # Play Framework - The High Velocity Web Framework
Z

2021-04-06 10:48 UTC, r0gergunn commented on README.md
>  # Play Framework - The High Velocity Web Framework
p

2022-08-18 08:19 UTC, closed without merging